;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Gun.Actions.Equip",DevComment="")
+GameplayTagList=(Tag="Gun.Actions.Reload",DevComment="")
+GameplayTagList=(Tag="Gun.CanFire",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.AbyssFang",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Corroder",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Corvex",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.CraterLine",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.CrimsonHelix",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.CryoLance",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Eclipser",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Fragard",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.GlacierBeam",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Inferna",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.NullShard",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.OverVolt",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.PulseBreaker",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.RadiantEdge",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.RiftBurn",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Slagstorm",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.StormLine",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.ThunderJaw",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Toxin67",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Tundrave",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Weapon1",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Weapon2",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Weapon3",DevComment="")

