;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Gun.Actions.Equip",DevComment="")
+GameplayTagList=(Tag="Gun.Actions.Reload",DevComment="")
+GameplayTagList=(Tag="Gun.CanFire",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Weapon1",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Weapon2",DevComment="")
+GameplayTagList=(Tag="Gun.Weapons.Weapon3",DevComment="")

